"""
Problem 5 - Identifying Unknown DNA Quickly

Problem

The GC-content of a DNA string is given by the percentage of symbols in the string that are 'C' or 'G'. 
For example, the GC-content of "AGCTATAG" is 37.5%. Note that the reverse complement of any DNA string 
has the same GC-content.

DNA strings must be labeled when they are consolidated into a database. A commonly used method of string 
labeling is called FASTA format. In this format, the string is introduced by a line that begins with '>',
 followed by some labeling information. Subsequent lines contain the string itself; the first line to 
 begin with '>' indicates the label of the next string.
In Rosalind's implementation, a string in FASTA format will be labeled by the ID "Rosalind_xxxx", 
where "xxxx" denotes a four-digit code between 0000 and 9999.

Given: At most 10 DNA strings in FASTA format (of length at most 1 kbp each).

Return: The ID of the string having the highest GC-content, followed by the GC-content of that string. 
Rosalind allows for a default error of 0.001 in all decimal answers unless otherwise stated; please see the note on absolute error below.
Sample Dataset

>Rosalind_6404
CCTGCGGAAGATCGGCACTAGAATAGCCAGAACCGTTTCTCTGAGGCTTCCGGCCTTCCC
TCCCACTAATAATTCTGAGG
>Rosalind_5959
CCATCGGTAGCGCATCCTTAGTCCAATTAAGTCCCTATCCAGGCGCTCCGCCGAAGGTCT
ATATCCATTTGTCAGCAGACACGC
>Rosalind_0808
CCACCCTCGTGGTATGGCTAGGCATTCAGGAACCGGAGAACGCTTCAGACCAGCCCGGAC
TGGGAACCTGCGGGCAGTAGGTGGAAT

Sample Output

Rosalind_0808
60.919540

"""

#regex
import re

#read file into strings
fileToRead = open("C:/pycode/rosalind/rosalind_gc_input.txt","r+")

def GCpercenter():
	#strip any extra stuff and make a blank list
	content = [line.rstrip() for line in fileToRead]

	entriesCount = 0
	#find out how many entries there are
	for entry in content:
		if entry[0] == ">":
			entriesCount += 1
		
	tempToWriteBases = ""
	fastaName = [None] * entriesCount
	fastaBases = [None] * entriesCount
	textCount = -1


	for entry in content:
		if entry[0] == ">":
			textCount += 1
			tempToWriteBases = ""
			fastaName[textCount] = entry
			
		else:
			tempToWriteBases = tempToWriteBases + entry
			fastaBases[textCount] = tempToWriteBases
		

	#strip out the >'s in the names as they aren't in the example
	fastaName = ([s.strip('>') for s in fastaName])

	#loop through on function that does the gc content numbers
	counter2 = 0
	highestGC = 0
	highestGCName = ""
	for sequen in fastaName:
		#set up blank counters
		aCount = 0
		cCount = 0
		gCount = 0
		tCount = 0

		
		# split the input into individual bases
		inputSplit = list(fastaBases[counter2])
		
		#work through each on to do the counting, at this point we don't care about it only doing capital letters
		for i in inputSplit:
			if i == "A":
				aCount = aCount + 1
			elif i == "C":
				cCount = cCount + 1
			elif i == "G":
				gCount = gCount + 1
			elif i == "T":
				tCount = tCount + 1
		
		gcPercent = (gCount + cCount)/(gCount + cCount + aCount + tCount)
		if gcPercent > highestGC:
			highestGC=gcPercent
			highestGCName = fastaName[counter2]
		
		counter2 += 1
		
	highestGC *= 100
	print(highestGCName)
	print(highestGC)
	
GCpercenter()



"""
INPUT:
>Rosalind_4402
ACTAAGGCAAGAAATACGTCGTCGCGGGTTCAACCTATCAACGTGTCCGCTCACGGAGTA
TGCATGCGACGTAACTTTTTAAAAGAAGTCATGTGCTCGGGGATCACCTTTTTGCAGCAC
CTTGTTGAGGGTGTGGGAGATCTGTGTTCCCATACCGACCGTTCCTCCAAAAGATTTACG
CCGACCTCCAATCCCGTGGACCGCAGCTTTAGACGCACAAGGCATGGTCACTTTAAAGTC
TCTCTTAGGATTTTGTTTAGCGTCATTCAACAGGGATCTGCCCGGAGACTTTGGTCCTCA
GAGGGGTTGGACGACAGCCCCGTGTTCGCAGTTCCACCGTCGGGCACCCGATGCGTCATC
ATAACCGTACACAAGGAAGCGAGATTCCATAAACGTACAGGGAACTTCCTTCCCAGATAG
GCACTAAACACCCAAGACGCCACTCCGTAAGGCGCCCACACTTCAGTCCGCACCTTCGAT
TTAGTCTGCACCTCGAATAATTAGGTCTCCTCACTAAAGAGAGCCCTGTGAGAGGGTCAA
AGAGGGCGCATCACCTTTCCGACTCACTGAAGCTATAACAACGCATCCTGAGCACGACAG
TAAAAGTGAAAAAGTATTCAGACTAGCCACAGATGTCTGCGTAACCAACCCACCAGCGAC
TCTAACCTGGTGGAGGGGGGGAACCGTACGCAACAAATCTAGTGCCTCGCCATGCGCCAA
CAGAACGTGAGCGGCTTACATCTTACTACTCATGTTGGATTCCTAGCCACTGGCGTGTCA
TAGGAGTAGATTACTTTTTCGTGACGGGCCTGCCGGCGCAGATACCAGGCAAAGCAAAGG
CCCTGCGTTGGGCTTCCAGTGACCGTGGTACCTGGCACTCCACACCGCACTTATGTGCTG
AGGATGCTCAGGCAATACATCACGAT
>Rosalind_9926
GTTGTCTCTTACCTTATCTCCTCTGCAGCCAGTCATTGCGTGTTGTACACCTGCGTGCCC
GGAAAAGTGAGTAGGGAGGGGATAGTTCGTCGGAGGGTAGTGGCAATTGCGGTATGTGGG
GGGTATGGAAGTTAATGAGGCCGCTCCTGCCACGTCAAAGAAAGAACAAGAGCGCCAACA
ACGTCAACCCTTGGAATAACTCATTAGTGTCACATCAATGTCTGGTGCTAGGGCCATAAT
GTTAGGATACTTAAAACAGGAACTCCAAGATGTTGCCGACCTATATCGCATAACTCTGAT
CTGACGCTCAGGCAATTAGACTAGCAGCATACGGTGTCTAGATTTGGGCGTCCATACGCG
CGCTTATTTCAGGGCGTGTGAAATCCGCGTATGCCATACGCCGTTTAGTAGATGCTTTGG
CACGGGTGTTGACAGAGCAGACTACTAGATCTGCCAAGGGACACAGGACAAACTGTTCGT
CACAGATCCGCTATCAGGGATGTCGCGGGCTGAAGGGCCGACGCCCCAAGACTGATTCAC
TTTGACCGTATTGGGTGGAATTAGTGACTCGTTCCAAGGTGACGTGCATTTAGGGCTTGA
GGAACACTAAGCTTAGCTTTACGTATGTAAGCGTTCAATAATTTCAGGGGCGCGTTAAAC
AACTGGTGTCTTGGAGATTGTCTGACTGTCGTGCTGCCAGGGCTTGATAATCGGTTCGTA
CTTGAGGCATGTTTTTAGACATTCACGCCTTCCTGTGGCCCTATTCCAATTTCAGGCGCG
AACTTGCCTTCGCTAGATAGTCAGAGGCTTCGTGTATGTTGGTTGTCTGACGAGACGCGT
GTGAACCTTCGCTGGGGCATCGACATACTGATCGAACCAGGCGCCTTGTT
>Rosalind_5627
GTGTATGAATGATAGTACCAAGCTCGACGCTCGTTTACCAAGTGCTCCACTCTAACACTA
CTGACTATCAGCAGTAAGATATTAAGATGTGATTTCTATGACAAGTAGTTTCGTTGTTCT
TACGAACATAATCTAATTGGCAATAGCGTCAACGTTTCTCGGGCTCTAGAGTAGGAGTCC
AACGGATTTAATTTGGAGGGAGAGCTTGAACAAAACGGATGGCCTGCCCCAATTATAGCC
ACTTTACTCTCAACTCAGTCCCTATAGCCGTCTTGAGGGCCTCGAGCACCCATATGCCTT
TGCCGCTAGATACTCAGGCCCGGCGGAAGATGTTGAACCGTGGGGACAGTTTTACGGTTA
GGTCTAAACTCGCGGCTTTCATAGTATCCAATGTTACGCACAAGCGCAGGTCATAACATT
TTTGAGACCGCTTTGCTACCCCAATTCGCGGAAAATGTGAACAGGCCCTTTATGGGCAGT
AGAGCTACTCACCACATTAGGAAGGTGCTAAAGATCCAAGTCCCGACCTAACCAGACCCT
AACTCCCCCCTGGTTCGGAGGTGCAACGTTAGTGGAACGGTGTTAGATTGACCGAGTGCT
CCGTACTACAAGCCCTTATAGTATCAGAGAGCCCAGCTTCCTCTGGTGCACGATTGATTG
CAGGGCCCTGTTAGAGATGACCACCTGCCGAGCGCGACCTTTTGTCATATGGTCCAGGAG
GCACCTTGCGTACATATTGTTGATTCTCACAGCACATTACTAAGGCCTGCCTGACACGGT
CTAATGTGCACTTAGGCCGCTTTTCCAGCCAC
>Rosalind_5966
TAGGGTACCATCCACTATCGTTCCCGCGCCCCATTAAACGGTCGGAGATCTACCTCTACT
AAATCGACGGGGGAGCGGTTGTAGTAGCTCGTAGGCACTCTTGGCCCAGCGGTAAAGCGC
GAGCGCACGACTTGCTTTTAGGACTGAACTAATATAGGGGGTTCGCATGGGACGAAAGAC
CGCCCGCTGCCTGCATGAAGCTTTGTCGCTGTGTGTTGCGGGCGTCCGACACACGCAGCC
TGGAGGGAGCCCCCACGGGAACCAGGGCGCACGCTACTTTCTTGAATAACTTAGGTTGTC
ACTGACGTAAAGATCTAATGCGAGGTTACGGGTTCAAAAAGTTTGAGATGACCACTTACG
TAACACTCACGACCTTAATGTGCCATACCGCAAAACTCGCCTATTTGCACGAGTATGGGA
GGGTCAACAGTGAGTTACGGGATTGTAATCTAGACCAGCTTGGACCTGGCCCACAAAGGT
GCGCTCGCATGAACGTATCGTGAGACCCCGTGCTTCGAACTGAGATGTACATTCCACTGA
CGATGCAATCTCTTTCACCGATGTATTTGCAGTCAGACTATCTGGTGATGCAACCCGCGC
TCTTGCACCTAAAGCTTATTCCACTGTCTCGCATTCAATTCACGCGACATGCGTAGAGCT
TGCCTTAGCCGTAATTCAACGGGAGGATTTGGTCAGCTGACCGGTTCAACCTTCAGAATT
ACCCGTACGACTATTAGGTCGATCTTCATTTCGTACAGAATGGTGGCACGGTTTACCTAC
CGTATAAAACCTGTTTATGATGCCGGGATCGACTCCCATTTCTACTCGACAACACCGGGG
GGTTGGTCATGGCAATGCTAGTTTGTGTACTCTCGCGATGGGG
>Rosalind_4065
GTATCCGCTAAACAATATGCACTGCTATTATTGCCGCATGTTAGGTTGTCGGGAGCACAT
GTCTTTGCATCGGTCATGCAGCATGCGTGTCGGAAGGTTGAAGATTTGAATGTTTGCTCG
GTAATACGAACTCCACTAGAGGGCCCTCACTACCAAGCTCGTTGAGCCTCTGGCTCACAT
CACCCCTCGTGGCAAAATGTAGGGCGCCACACACCGGCTGAATCCGACCTTATCCGTTTG
CACGCAGACCAGGGCTGACCTTTTTATGTTTCTCACTGCTAGCCTGTGATACGAAGATGC
CAGCGATTACTCAACGTAGTATTAGGAACACAACACATTGAGTAGAATCGGAAACTGAGT
ACAATAATGGCAGCCTGATAAGGGCAGGGTCTGTGCGCGGAGAACCGGAGCTCGCTCTAC
TGACAGGTTTCTGGGATTATGTGGACTGGAAGTTCTCGCGTGACCTATGTTCAGACATCA
TACCAAGCTCATACGCGGACAAGTCTACCGACCATCAAGTCTCGAGGACGCCCAGCTGAG
CCTGCTTTAGCCAAGTTTTCAGTGGTAAATTCCAAGGGCGTCTAGAAATCTGCGGGTGAA
TATGTATTCCCAGACGTCTACAGGTCAAACGTCCTATTTGGTTCCGTACATTAGATCCTC
TAGGTTCGAAATTACAACTGAAGGACCCGCCCTTAACTTCTCTCGGAAATTAATGACCAA
CGACCGTTTGACCAGTTAACACCAGTCTATGGTACCGAGTTCATGACAGACATGTGCACG
ATCACCCCTGGTTGGGGGGGTACTGAATGTACCCTAAGGGTGATGTTGCGAATCATTTCA
TGAGACGGATGTAGCATCCCTGCGACCGCGCGATCCTCATTCAGCAGGTGGTAAACGTAG
ATTTAAAAAGAATGAGTCTAAGGAGGGCCG
>Rosalind_3146
CAGTGGCATTAAATGAAGTCTATCTCCGTGCCCTCTTGGACACGGTTACGTGGGCTAGTA
GTCCTCACCGGCGTGCGCATTTAGAGGTCACGTACCGTGTAATAAAGATAACTACGTAGA
ACCATAAAGCAACCAAACGGATCGCACGCCACCCACAACAGTCAGTACATATTCACAGGC
AGGCAGCCTTCAGGGGACCCACGGTGCTTTGAATGCAGGCTCATGGGGTCTAACATGATC
ATACCGGCGACCAGGGGTGAGACTCATGTTGAGGTGGGTTCACAACTGAAGCGCTCCACA
GCGGGGCGGTCCGTAGTACCTCTAATAGACCGTGCTCGGTACGAGTGGATCATACGGTCC
CCTGTCTGTTCCCACCACTAACGCCGCGATAACTACTTATGTAAAGCACCCGAAAGCCTA
GGTCTAGAGCTGGCTTAGCGACCCATGATTTCATAAATAAGTCGCGAGCGGCAGTTACCG
AGAACTCGTTAAACTAACCATCTAGCCCCGTCGTACCGATTAGCTTCACTTCCCGCTTCG
TAGGTTTCGCACAAACACTCCACAAATCAGCAGCCTGTAACAGAGACACCATCAAAATTC
TTTCTAAACTGGACCAACACAGGCCTTCTGATAATTTTGATAATATGTCGTCCAAAACGC
CGCCGTTCGTCATTAGCGATACAACTAGTAACACGGATCAACACCGTAGCAGCGAGCGTT
GGCGCTACCAGATACCTCTCTGGGTGGCGGGGTGAACAGTACACCTCTTGGTAGGCAACT
ATGATTACTGATAAGAAATATTGAATTTCGCACGTAGTCGTGTGGACTACGATCAGACTA
ATCTGTCCCGCTGACACATGTGTGACTACTACTACCCTATACGCACCACAGCCGTCTGTA
TTGATGCTTTAAGATACCTTTACCAGCACCTACCTCCCGTCTACGCTCCTCTATTCACAT
GTTCCAACCTTT
>Rosalind_9777
GGGTGGTTAAAACGAAGGCAGGGGCTCTACTTTCAATACATACATCACCGCGTAGGACTG
CTCACCCTGAGAGTATCTAGATCTCTTAGCCTTGTAAGCTACTGTGTGGTATTGCAAACA
TGTAATCCTGGACGACGGTGAGTGGATCATGTGGGTTCAACTTTAAAGCCGAACCTCAAT
GAGGAGGCAACTGGTCCGCGGCATGGGTAGGATTACGGGAGTAGAGACGTACTTGGACTT
GGCAGAACGACCGCGTGTCAGCAGCTCTACGATCACTCAAGAGGTGCTTGTTGATGGTGT
GTACACAAATCGCAAAGATATACTAGAGCGGCCAGCAGCCGTTGTGAATATGTCATATGC
GTGACATAAAGCCTAACACACAACCACCAGCGGATAGCACTTGCCAAGGTCCTGACGCTT
GTATGGCTAGGGCAGCGTTTCTAGCTTGCTCATGCAGTGTCCTGAAGGTGGACGCATGAA
GGGTGGGTGCCCCCCGCGAACAGACAGGGTACCAGTCGTAGTTCAGGGCGGGCGCACACA
AACTATTTTGTTAAAACGATCGTGGCATTTTTTATGGCGGCGTTAGTGAGTCACGCTCGC
ATGAGATAAACTTAGATCAGTGGGTAGAAAGCCAGCACTAAAGTGGTAAAGTGACTAATC
CCCTGTACACCACAAACAGAGATGGATGGCGCCCCTTGATCTGCAACGTACTGACTCAAT
ACTAATGGAAAGTGTGTAAACTAGTATTGGACGAGTTTGGGGATGTCGCGGGTGATCTAC
CGACGCCCCACTTAAGTGCGGTAGACGCAATTCTAGGGGGAACATCCTTACCACGTCATC
TATCCAGCGCTGGATCGCGGGACCGTGCAACGACGTAGAGCACAACTTCTGTATTATAGC
GGTGAAAGCTCCCTTCAATCGTAAAAGTTGTCTC
>Rosalind_3399
TAAGGGCGGGGGAGACGGTTGAGACATAGGCCTAATTATGACGGTGTCGCACCAAACTGT
CGGACGCGGATGATACATCGGTGGGCTTAGACACCCCAAAGTGCCCTTTACATGAAAATG
GTAGTATTACATCCTGTACTCGGATTCGTAAAGGCATAGGGGAAAGTGTGGAGGCAAATA
CATTCGGCCACAGCCCCAGAAGTTGAGAAGATGTCGCGCATTCCGCGCATCGTAGCTCCA
AAAAAGCCGGCATCTTATTTCCATAGGGATTGCCGCTCGTAACTCCGAACGTCACACTCG
TCCGGTACAGAGGGTAACCCGCCAGAAACGGACCATATTTCGATTCGCGAAGAGATTAGT
TGACGCCCCCACCTTCTGTGGTGCGCCCGAACCAGCTTAAAGCTCAGGAATCTCGCACTA
TCACACATTACTGTACAGGTGTGGCTTCACCCCTGCAGGCGCTCCAGAAGAAGGGCAAGG
GCGTGCGCTCGAGAAACCATTGAATGTCTCGCATTTAAGGAGGATTAAAACACCCGAGAC
CCAGTTAACAGTGATCTGGTCGTATGACGGAGCCTACCAACATGTGCAGAGGGCCAGCGG
ATCCCCCTAAGCTTGCGGAGAAAGACCCTCGAACACCTGATGTCCTGACATCGGTCTCAC
ACAACTGGCTAGTTTGACCTGACCAGCATTGGCCTTCCTGTTGCTATCGCATTTCGTGGC
TGCATGGCCTTTAAGGGCTGCAAAATACACCGTGTGAAGTCAGCAGGCGCTGGTCCCGAT
TTATCGCCGCCGAGAGAGGTACATCCCCCGCGGTGACCAGAGCGGTTGCCTGAGTAGTTC
TCCGAGATGTTTAGGACTTGGACCGGGTACCCCCGCTGAGT
>Rosalind_9866
CGACTGTCCTTATCAAGAATACTTCTGGTGTATCTTTGTCCTACCATCCAGGGCAGATCT
GGAGTTTGTTAGCATACTAAACTATGTGCATTGCCGTTATTCCACATGGGCCATCTGGTG
AGTGGTATCCCCGCGAACGTGCTTTTGCCGCTACTGGTGAAAAGTTCTCGTTGGGTACGA
ACATTGTCACACTTCCAAGCACGTTAACTATCTACTCTACATGCGTTGGGACCTTTAACA
TGGTTCCTGCGCCGTCACGCCTTATGCAGCTGTCCGTATTCTCATTGATGGGTTATCGTT
AACCGCAAGGATCCCTTATTCGTGCGAGGGTATACCTCACCGTTCCATGGACTAGGGTTA
TACCTATGCATGGTCATGGGCCTAGTCCGGTCGATTCCCACCCATTGGTGTATCCCGCGC
TAAGGGCATAAATAGGCAAGGCAATCTGTCGTGATCAGGGGTAGTACTCAATTATTCGAA
GACAGTGTGAGGCCGGGGAATCGGCATATCGATTAGGGGGGTTCAGAGGCCGCGTGTCTT
CCCTCGCTTCTAATTCATCCTTTAAATCGACGACGAACTGATAACGCCTAGGACGACGGG
ATAGGTCGTTGTCAACCTGTATGCATTCACAGACCGCCCATGGCACAGTACATCAAACAT
CTCCAATTAGTGCATGTTCTAGAACTGTAGTTTACTAACAAATTAGGGCTAGACAATAAA
TATCTCTTGCCACTAAACTATAATCAGGGAATTCGTACGGTTAGGAAATTAAAGGCTCGG
AACGGTTCCGATGCATACTAGACGGGCAGGCCTAAGACCGTCAAGGACGTTTCAAACCGT
AGACTACACTGTGTATCGTGTTGTACGAGTTCGAGATACGTCGGACATGGGCACGCCT
>Rosalind_1272
AAGAAACACGCGGGTCTTGCACCCAACACTCACTGGTGGCCATGTAATACATTAGCCGTA
TATATTTGGGCATGCATTCTTCTGGAGGGGTCCTCCATATTGTTCCCAGGGTTTCCAGCT
CGCCAGTAATATGCAAGTTTTGAATCCGATGGCTTACGACAGGTTTGTAGAATGATGAAG
CTGCTGCTAACAATGTATGAATTACAACCCGACCTATGTGTGCTGGGTGTACGCGCTGGG
GAAACCATTCTATAACACCCATGGAAGGACCACAGTCTCGCTCCCATACCGGGACTAGTA
AATATGCCAATCGATCGATGACGTGGCCGATCGTTCGGGCCATGTCTGGTTCACCATGAT
TTAAGGATGCATATATACATATATGGACGCGAACGCTAATGGGGTTCATATACTGTTCAC
AATACGTACGGACAGCCAACACAAAATTCTGCTACGGGCGCTTGGCGTTACACCTCAATG
TACAGCCAGTCGTACCAACCAAAGACGCCGCTATATTTCGGTCATTGTTTCTACCGATGA
GATGGCACATCAGCGGTCGTGCCCCCGATATAAATAAGCTCCAGCGATGTGTGCTACTAG
ATGTGGGCATTACGTTGAGCTGAGGAACTACCTCAACTTAATAAGCTCAACGATAATTCC
AGGAAAGTTGTATCTCCACAGCGCGTACTGTCATCGAGCACACTGACTTCTTACAGCTGA
GAAGCTACCATACAGCAATTCACTAATGCCAAGACCAATTGCCTGAAGCGGCGTTGCCTG
AGTTAGGGACAGTAATTCTTTGTCAGCGCATGGATTGCATCTACTGAGAACGTACGGTGA
TGGTATTACT




OUTPUT:
Rosalind_3399
53.802497162315554
"""