"""
Problem 3 - Complementing a Strand of DNA

Problem

In DNA strings, symbols 'A' and 'T' are complements of each other, as are 'C' and 'G'.

The reverse complement of a DNA string s
is the string sc formed by reversing the symbols of s

, then taking the complement of each symbol (e.g., the reverse complement of "GTCA" is "TGAC").

Given: A DNA string s

of length at most 1000 bp.

Return: The reverse complement sc
of s

.
Sample Dataset

AAAACCCGGT

Sample Output

ACCGGGTTTT
"""

def revComp():
	print("Input the DNA string to be reverse-complemented: ")
	inputString = input()
	
	#make a blank final answer list and convert the input into a list
	inputRevComp = []
	inputToList = list(inputString)
	
	basecounter = 0
	for i in inputToList:
		if i == "A":
			inputToList[basecounter] = "T"
		elif i == "T":
			inputToList[basecounter] = "A"
		elif i == "G":
			inputToList[basecounter] = "C"
		elif i == "C":
			inputToList[basecounter] = "G"
		basecounter +=1

	inputToList.reverse()
	inputRevComp.append("".join(inputToList))

	inputRevCompString = inputRevComp[0]
	#for display 
	print("reverse-complemented:")	
	print(inputRevCompString)

revComp()

"""
Input the DNA string to be reverse-complemented:
AATCGGCCTTCGCGGTGATAACAGGGCGTATGAATGCTACCGGAACACCGGCTCCGTATATTTTACACATTTTAATCCGAGAATCAATTACCACCATCTATGAGAACATGTGAGCACCATTTTTGGGCCCCGCCCCTCGACCAAAGGTGTCTACTTTGTAAGAGCGGGCCCTTTCGTGTTGCCCATTACCATTTCATGGGTCTAACCACCACTAGGAAGTCACAGAGGAGGTGCGCCGAGTTCTTATGTGTTCGGCGCGGACAAATCCGACGTTTTATTGTACGACCTGTGGTTGAATCCGTTCGCATTAGCCCAGCACCAATATCGACATCAGGCGATCGGTTCAACCTATTTTTTGGGAACCCAGCGCCGGCCAACACTGTTATGCAGGTTTTATCAGAGTAATCCGACGCACCATCTCAGTGGGGTCCGATATGAATTTACCACCAGTCACAGACTCTTGCTACATAACCACTTATCGCGAGTAGTTGGAAACCCGTACATTCGGACATCCTGAGGGGTAATCTAGAGACTATGTCCCTGAATGTGTTACGCGTGTCAATCTGGCTCTCAGTTCTGGGAGGCAGGGACCCATCCTTTAAGTTCGACTAACATGAGATAATTGCCTTTGCGGATACAACGAAGAGGTCGCAGTAATTGCTCCTTACATTCCTGCCCGAGCTGCAGCGTTAATTAATACTCTCTGATACTCCGATTGCCGCTAGCGGTCGGTCTACCCCATTTCAGCGAGTCTTTTCCCTATACGTTTAGACCACCTTAAGCAAAGCCATCACCGTGCCTGCCTGTCGCACAAGTATGAGCACGAGCCCACGG
reverse-complemented:
CCGTGGGCTCGTGCTCATACTTGTGCGACAGGCAGGCACGGTGATGGCTTTGCTTAAGGTGGTCTAAACGTATAGGGAAAAGACTCGCTGAAATGGGGTAGACCGACCGCTAGCGGCAATCGGAGTATCAGAGAGTATTAATTAACGCTGCAGCTCGGGCAGGAATGTAAGGAGCAATTACTGCGACCTCTTCGTTGTATCCGCAAAGGCAATTATCTCATGTTAGTCGAACTTAAAGGATGGGTCCCTGCCTCCCAGAACTGAGAGCCAGATTGACACGCGTAACACATTCAGGGACATAGTCTCTAGATTACCCCTCAGGATGTCCGAATGTACGGGTTTCCAACTACTCGCGATAAGTGGTTATGTAGCAAGAGTCTGTGACTGGTGGTAAATTCATATCGGACCCCACTGAGATGGTGCGTCGGATTACTCTGATAAAACCTGCATAACAGTGTTGGCCGGCGCTGGGTTCCCAAAAAATAGGTTGAACCGATCGCCTGATGTCGATATTGGTGCTGGGCTAATGCGAACGGATTCAACCACAGGTCGTACAATAAAACGTCGGATTTGTCCGCGCCGAACACATAAGAACTCGGCGCACCTCCTCTGTGACTTCCTAGTGGTGGTTAGACCCATGAAATGGTAATGGGCAACACGAAAGGGCCCGCTCTTACAAAGTAGACACCTTTGGTCGAGGGGCGGGGCCCAAAAATGGTGCTCACATGTTCTCATAGATGGTGGTAATTGATTCTCGGATTAAAATGTGTAAAATATACGGAGCCGGTGTTCCGGTAGCATTCATACGCCCTGTTATCACCGCGAAGGCCGATT
"""