"""

Problem 2 - The Second Nucleic Acid 

Problem

An RNA string is a string formed from the alphabet containing 'A', 'C', 'G', and 'U'.

Given a DNA string t
corresponding to a coding strand, its transcribed RNA string u is formed by replacing all occurrences of 'T' in t with 'U' in u

.

Given: A DNA string t

having length at most 1000 nt.

Return: The transcribed RNA string of t

.
Sample Dataset

GATGGAACTTGACTACGTAAATT

Sample Output

GAUGGAACUUGACUACGUAAAUU


"""
def rnaTranslator():
	print("Input the DNA string to be translated to RNA: ")
	inputString = input()

	# split the input into individual bases
	inputSplit = list(inputString)

	#work through each on to do the counting, at this point we don't care about it only doing capital letters
	basecounter = 0
	for i in inputSplit:
		if i == "T":
			inputSplit[basecounter] = "U"
		basecounter += 1	


	rnaJoined = "".join(inputSplit)

	#print the output
	print("The RNA translation is: ")
	print(rnaJoined)


rnaTranslator()


"""
Input the DNA string to be translated to RNA:
GATTCCGACTTTCTCCAACCCACCCCGGAGCAACACGTCAGTGACTCTGTATACCGACACTGCGAGGTACTGCCTGACTTCAGCTTTAAAGTGCCGTCGGAGACCCGTGCCACCACCGACTAGCCACAAGGAGAAAAATTGCCCTGCGATTGCGCCAGATCGGATTAGATAGATTCCGTTAGTGCGCCGCAAAGTCCTCCAAATCAAGGCATATATACGCCCGGACTCCAAATAGTGATATTTAAATATGCGTCGATGAACCCACAGTGATGTAGTCGCTCTCCGCTGAGGTAAAGTCCACATTCGAAGGCAACTGTTCAGAACGATGGACACAAGGGTACCGTATTTGGCGGCGGCCCCTTGCCCCGTCCCTGCCTGGTACGTCAAAGCATACCCAGCTGTTTAACTACATACAGCTAAGGCGAGGGGGCCGGCGTCTGGCGGTCTTGTTGGAACTCACTCCAAATACTGTAGTTTCTGCCTTTCACGTTCGCTACGTGAGCTTGTCCTTACGGTTGGAAGGGGAGCTGCATTTTTAAGTGTAACAATGGCGTTAAATCCTGGTCTTTTGTTTGGGATCGCTAGGTACTCCGCAAGTATGCGCTATCCTCCTCTCTGGATACTCGGCACGACGGTTCCTTGCAGTAGCACAACGCAGCTAGAGAGCTGAGGTCATTACCTTAGGCGATTATAAGCAACCCGGCTCCCAACTATACTTTGTGGGTCCGCGGCTATCTACTTCCAGTTTATCGATGACGCCTCCGCTGAAACGATATTATGTCTCCCCGCTCCTTTCTAAGTGCATAAGTACTCGGGGGCTACAGCGCATACACATCTTCACATCAACATTACTACCTTTCCGAGCGTAGAGACAATGAAGAGGGGCCCCATTGGAGCGTTATTCACTCCGGGTGATGAATTCCCCTACATGGGGACGATTAGACAATGGGGCTTTCTGCA
The RNA translation is:
GAUUCCGACUUUCUCCAACCCACCCCGGAGCAACACGUCAGUGACUCUGUAUACCGACACUGCGAGGUACUGCCUGACUUCAGCUUUAAAGUGCCGUCGGAGACCCGUGCCACCACCGACUAGCCACAAGGAGAAAAAUUGCCCUGCGAUUGCGCCAGAUCGGAUUAGAUAGAUUCCGUUAGUGCGCCGCAAAGUCCUCCAAAUCAAGGCAUAUAUACGCCCGGACUCCAAAUAGUGAUAUUUAAAUAUGCGUCGAUGAACCCACAGUGAUGUAGUCGCUCUCCGCUGAGGUAAAGUCCACAUUCGAAGGCAACUGUUCAGAACGAUGGACACAAGGGUACCGUAUUUGGCGGCGGCCCCUUGCCCCGUCCCUGCCUGGUACGUCAAAGCAUACCCAGCUGUUUAACUACAUACAGCUAAGGCGAGGGGGCCGGCGUCUGGCGGUCUUGUUGGAACUCACUCCAAAUACUGUAGUUUCUGCCUUUCACGUUCGCUACGUGAGCUUGUCCUUACGGUUGGAAGGGGAGCUGCAUUUUUAAGUGUAACAAUGGCGUUAAAUCCUGGUCUUUUGUUUGGGAUCGCUAGGUACUCCGCAAGUAUGCGCUAUCCUCCUCUCUGGAUACUCGGCACGACGGUUCCUUGCAGUAGCACAACGCAGCUAGAGAGCUGAGGUCAUUACCUUAGGCGAUUAUAAGCAACCCGGCUCCCAACUAUACUUUGUGGGUCCGCGGCUAUCUACUUCCAGUUUAUCGAUGACGCCUCCGCUGAAACGAUAUUAUGUCUCCCCGCUCCUUUCUAAGUGCAUAAGUACUCGGGGGCUACAGCGCAUACACAUCUUCACAUCAACAUUACUACCUUUCCGAGCGUAGAGACAAUGAAGAGGGGCCCCAUUGGAGCGUUAUUCACUCCGGGUGAUGAAUUCCCCUACAUGGGGACGAUUAGACAAUGGGGCUUUCUGCA
"""