"""

Problem 6 - Evolution as a Sequence of Mistakesclick to expand

Problem

Given two strings s
and t of equal length, the Hamming distance between s and t, denoted dH(s,t), is the number of corresponding symbols that differ in s and t

. See Figure 2.

Given: Two DNA strings s
and t

of equal length (not exceeding 1 kbp).

Return: The Hamming distance dH(s,t)

.
Sample Dataset

GAGCCTACTAACGGGAT
CATCGTAATGACGGCCT

Sample Output

7

"""

def hamGetter():
	
	print("Enter the first DNA string: ")
	dna1 = input()
	print("Enter the second DNA string: ")
	dna2 = input()
	
	hammyCount = 0
	
	if len(dna1) != len(dna2):
		print("Those weren't the same length, buddy!")
	else:
		dna1list = list(dna1)
		dna2list = list(dna2)
		loopcount = 0
		for base in dna1list:
			if dna1list[loopcount] != dna2list[loopcount]:
				hammyCount += 1
			loopcount += 1
			
	print("Hammy (Hamming) count is: ")
	print(hammyCount)
	
	
hamGetter()


"""
Enter the first DNA string:
AGCTTCGACAAGGGCTGGGCGCGGCCGTTCATACGCCGCTGAATAATCTGCCAGCTGACAAGCTTTACACTCCCACACGTCATACGCGGGGGCCAGTTAGATTAAGCCCCTCGCAACCGCGCAGGACCTCCTACCGCTTCAATTGTAACTCCTTAAGAGCGCCGTGCAATTGTGGCTCGGCATGAGTGGTGTCCAGAGACGCACAGACCTTGCCGTTTAAAGCTTTCCGGCTTTATTTATCGCTTCGTTTTCTGTGATACGTTCCGCCCGGAGGAGAGACTTTAGCACTTCGGGACTAGCATTACAGGATCCTGTGTTTGATAGTATACCGTGATGAAACTGAGGGCAGTTTGGGACACGTTACCATAAGACGGCACTCGAGGCACTCTAGTTGTAAACCTGCGGCGCCCGGACTTGTGTCCTACACGTAACTTTGGCTTCACTCACATTGTTGTAGTAACTTCCCTTACGATGCGGCACCGATCCTGACTAACCTCGGCCGCCTTGGAATTCCTACCTGTATCCCGCATATACATTAGCGGAATCTAGAAAGAGTCAAGAGGTGCACTTAGGGGTCAGGCGCCGAGGGAACAATATCGAGCCGGCAAGCGGGTTTCTTGCCGCCCCGCTATCAATGCATACATAGACGATTAGCGGTGGCGATGCCTGGTAACACATGGTGCGTACGACTGCCGGAGGGGTACTTGTGTTCTGGTTGGGATACGGTTTAGAGAACTAGTTCCATCCAACGGCGGATAGGATGCATCATGTCCACAAACACGGCACAGTACCTCGTTCCGTCGTCTTGTGTATAAGTATCGTGCTTACTCCAAAGGGTAGATGTGCAAATCACCGCCCATGAACACAATCGACGTAATCGCGTGTGAGTCATGGGTTACAACTTCGGCTTTGCAGTGCGGCCCTTGTGCCGGGTGGCAACAGGTCACACATCCGATCAACCCCGGCTACGCTTAAGATATCTAAC
Enter the second DNA string:
AACTAGGACATGGCCTTTGGGGGGGCGCACCTGGAATACCTGTAAGAATCTGGCCAAACAGTGTTTGCACAGCGCTAAGGAGTCCTCCTGCAAGAGTTATAACATCCCGCTCGCGCGCGACCAGTCCTCGCTACCCTTTGAATTTCAAGTCCTCGAAGCTGGGCGGCAATCGTCGTTCGGCAGCGGAGTTGTGCATCGACGGACACCCCGCAACAAATAGACCGTTACTCAGCTATTCACCGCTACGTTATCGCTCCTTGAGTCACCTCGAATTGGGGACGTTAACAACGCATGTAAAACATACCTCCGTCCTTTGCTTTAAACTGAATCCGGCCCACAGTAATCAATGATTAGGACACGTGTCAATATTACGGAGCTAGAGGACCTTTACTAGAGGTACCTCGGACTTCGAACATATGTTAAACATCTAACCATGTTTGTTGATTTCACTTTGGTTTAAAATTTCTTACGATCCGGAACGGAGCCTCCCATACGTCCGCCTTTATACCATCTCTTAAACTATCTTGACTAATCATCGGCGGATTAGAGACATCGTGAACGTGTGCCGGTAGAGCGCATGCTCCGAAGAAGTGATTGCGAATCGGAAGGCCAGTTTTTTTCCTCCCTGCGATTCACGGATCGATAGACGACTAGATGCAGAGTACGACTTTAACAACTGGGGGGCATACTCGCCGGAGGTTCGTTAGTGTTCTACCGTGATCCTCATGTACAGCACTCGATCTATCCAACTGCTTATCGGAGGCAGATTGACGATCAAGTTTGCATCCATTCTCGGTCGGAAGTGCTCTTAATTATGTTTGTGAATTTGCTCAAGGGGAAGTCAGAACATCTTACATCTGGAAGCCCGCCGCAGTTAGTGCGTGTGACCGGTACGTAACTTCAACCCTAACGTGGATACGACGTTGGGCATAGTGGCCGCGCACAACAATTCAGAGGCGGCGTGGGTTTGGCTTAGAAACGTCAA
Hammy count is:
479

"""